name: build

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro Max']
 
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        xcodebuild clean build -project Disorder/Disorder.xcodeproj -scheme Disorder -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      env: 
        destination: ${{ matrix.destination }}
